import { useEffect, useState, type Dispatch, type FormEvent, type SetStateAction } from 'react'
import './App.css'
import { type Account, type CalendarDay, type CashFlow, type DirectoryItem, type FlowDraft, type PaymentStatus, type User } from './apiFacade'
import { money, shortDate } from './format'
import { type LoginState, type Page, pageIcon, pageLabel, roleLabel, statusLabel, usePaymentCalendar } from './usePaymentCalendar'

function App() {
  const calendar = usePaymentCalendar()
  const [newDate, setNewDate] = useState<string | null>(null)
  const nameOf = (items: DirectoryItem[], id: string) => items.find((item) => item.id === id)?.name ?? id
  const accountName = (id: string) => calendar.accounts.find((account) => account.id === id)?.name ?? id
  const canMove = (flow: CashFlow) => flow.type === 'payment' && ['draft', 'approval', 'approved'].includes(flow.status ?? 'draft')

  return <main className="appShell">
    {calendar.user && <LogoMenu page={calendar.page} pages={calendar.availablePages} user={calendar.user} onPage={calendar.setPage} onLogout={calendar.logout} />}

    <section className="workspace">
      {calendar.user && <header className="topbar"><div><span className="eyebrow">{calendar.user.name}</span><h1>{pageLabel[calendar.page]}</h1></div></header>}

      {!calendar.user && <LoginScreen login={calendar.login} setLogin={calendar.setLogin} users={calendar.users} onAutoLogin={calendar.autoLogin} onSubmit={calendar.submitLogin} />}
      {calendar.user && calendar.page === 'calendar' && <><section className="calendar">{calendar.visibleDays.map((day) => <article className={day.hasGap ? 'day gap' : 'day'} key={day.date} onClick={() => calendar.setSelectedDay(day)} onDragOver={(e) => e.preventDefault()} onDrop={() => calendar.movePayment(day.date)}><span className="dayTop"><strong>{shortDate(day.date)}</strong><span>{day.hasGap && <b>Разрыв</b>}<button className="iconButton miniIcon plusButton" title="Новая заявка на этот день" onClick={(e) => { e.stopPropagation(); setNewDate(day.date) }}><i className="fa-solid fa-plus" /></button></span></span><Metric label="Приход" value={money(day.income)} tone="positive" /><Metric label="Расход" value={money(day.outcome)} tone="negative" /><Metric label="Остаток" value={money(day.endBalance)} tone={day.endBalance < 0 ? 'negative' : ''} /><div className="flowContainer">{day.flows.length === 0 ? <span className="placeholder">Нет движений.</span> : <ul>{day.flows.slice(0, 4).map((flow) => <li draggable={canMove(flow)} key={flow.id} onDragStart={(e) => { if (!canMove(flow)) return; e.stopPropagation(); calendar.setDraggedId(flow.id); calendar.setDragPoint({ x: e.clientX, y: e.clientY }) }} className={flow.type}>{flow.type === 'income' ? '+' : canMove(flow) ? '↕' : '•'} {nameOf(calendar.counterparties, flow.counterpartyId)} · {money(flow.amount)}</li>)}{day.flows.length > 4 && <li className="moreFlow">+{day.flows.length - 4} ещё</li>}</ul>}</div></article>)}</section></>}
      {calendar.user && calendar.page === 'approvals' && <Approvals flows={calendar.needsApproval} counterparties={calendar.counterparties} approvalLog={calendar.approvalLog} onStatus={calendar.setPaymentStatus} />}
      {calendar.user && calendar.page === 'register' && <Register approvedPayments={calendar.approvedPayments} accounts={calendar.accounts} counterparties={calendar.counterparties} onCreate={calendar.createRegistry} onExport={calendar.exportRegistry} onPaid={calendar.markPaid} />}
      {calendar.user && calendar.page === 'reports' && <Reports days={calendar.days} flows={calendar.flows} counterparties={calendar.counterparties} onExport={calendar.exportReports} />}
      {calendar.user && calendar.page === 'admin' && <Admin users={calendar.users} />}
    </section>

    {calendar.selectedDay && <div className="modalBackdrop" onClick={() => calendar.setSelectedDay(null)}><section className="modal" onClick={(e) => e.stopPropagation()} onDragOver={(e) => e.preventDefault()} onDrop={() => calendar.movePayment(calendar.selectedDay!.date)}><header><h2>{shortDate(calendar.selectedDay.date)}</h2><div className="actions"><button className="iconButton plusButton" title="Новая заявка на этот день" onClick={() => setNewDate(calendar.selectedDay!.date)}><i className="fa-solid fa-plus" /></button><button className="iconButton" title="Закрыть" onClick={() => calendar.setSelectedDay(null)}><i className="fa-solid fa-xmark" /></button></div></header>{calendar.selectedDay.flows.length === 0 ? <p>Движений нет.</p> : calendar.selectedDay.flows.map((flow) => <div className="flowCard" draggable={canMove(flow)} onDragStart={(e) => { if (!canMove(flow)) return; calendar.setDraggedId(flow.id); calendar.setDragPoint({ x: e.clientX, y: e.clientY }) }} key={flow.id}><span>{nameOf(calendar.categories, flow.categoryId)} · {nameOf(calendar.counterparties, flow.counterpartyId)}</span><strong className={flow.type === 'income' ? 'positive' : 'negative'}>{flow.type === 'income' ? '+' : '-'} {money(flow.amount)}</strong><small>{accountName(flow.accountId)} · {flow.purpose}</small></div>)}</section></div>}
    {newDate && <NewFlowModal date={newDate} accounts={calendar.accounts} counterparties={calendar.counterparties} categories={calendar.categories} onClose={() => setNewDate(null)} onSubmit={(draft) => { calendar.createFlow(draft); setNewDate(null) }} />}
    {calendar.user && calendar.page === 'calendar' && <FloatingSummary calendar={calendar} />}
    {calendar.draggedFlow && <div className="dragPreview" style={{ left: calendar.dragPoint.x + 14, top: calendar.dragPoint.y + 14 }}><strong>{nameOf(calendar.counterparties, calendar.draggedFlow.counterpartyId)}</strong><span>{money(calendar.draggedFlow.amount)}</span></div>}
  </main>
}

function LogoMenu({ page, pages, user, onPage, onLogout }: { page: Page; pages: Page[]; user: User; onPage: Dispatch<SetStateAction<Page>>; onLogout: () => void }) {
  const [open, setOpen] = useState(false)
  return <aside className={open ? 'logoMenu open' : 'logoMenu'}><button className="logoTrigger" title="Меню" onClick={() => setOpen((v) => !v)}><i className="fa-solid fa-wallet" /><span>Платёжный Календарь</span></button><nav>{pages.map((item) => <button className={page === item ? 'active' : ''} key={item} title={pageLabel[item]} onClick={() => { onPage(item); setOpen(false) }}><i className={`fa-solid ${pageIcon[item]}`} /><span>{pageLabel[item]}</span></button>)}<button title="Выйти" onClick={onLogout}><i className="fa-solid fa-right-from-bracket" /><span>{user.name}</span></button></nav></aside>
}

function FloatingSummary({ calendar }: { calendar: ReturnType<typeof usePaymentCalendar> }) {
  const [open, setOpen] = useState(false)
  const accountRows = calendar.accounts.map((account) => {
    const income = calendar.flows.filter((f) => f.accountId === account.id && f.type === 'income').reduce((sum, f) => sum + f.amount, 0)
    const outcome = calendar.flows.filter((f) => f.accountId === account.id && f.type === 'payment' && f.status !== 'rejected').reduce((sum, f) => sum + f.amount, 0)
    return { name: account.name, balance: account.openingBalance + income - outcome }
  })
  return <aside className={open ? 'floatingSummary open' : 'floatingSummary'}><button className="summaryTrigger" onClick={() => setOpen((v) => !v)}><i className="fa-solid fa-sliders" /><span>Настройки</span></button><section><details><summary><i className="fa-solid fa-chart-simple" /> Итоги</summary><div className="miniStats"><span>Остаток <b>{money(calendar.monthEnd)}</b></span><span>Разрыв <b>{calendar.nearestGap ? shortDate(calendar.nearestGap.date) : 'нет'}</b></span><span>К оплате <b>{money(calendar.approvedPayments.reduce((sum, flow) => sum + flow.amount, 0))}</b></span><span>Дней с разрывом <b>{calendar.days.filter((day) => day.hasGap).length}</b></span></div></details><details><summary><i className="fa-solid fa-filter" /> Фильтры</summary><div className="toolGrid compact"><label>Счёт<select value={calendar.accountId} onChange={(e) => calendar.setAccountId(e.target.value)}><option value="all">Все счета</option>{calendar.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Горизонт<select value={calendar.periodMode} onChange={(e) => calendar.setPeriodMode(e.target.value as typeof calendar.periodMode)}><option value="week">Неделя</option><option value="month">Месяц</option><option value="custom">Период</option></select></label>{calendar.periodMode === 'month' && <label>Месяц<input type="month" value={calendar.period} onChange={(e) => calendar.setPeriod(e.target.value)} /></label>}{calendar.periodMode === 'custom' && <><label>С<input type="date" value={calendar.customStart} onChange={(e) => calendar.setCustomStart(e.target.value)} /></label><label>По<input type="date" value={calendar.customEnd} onChange={(e) => calendar.setCustomEnd(e.target.value)} /></label></>}<label>Статья<select value={calendar.categoryId} onChange={(e) => calendar.setCategoryId(e.target.value)}><option value="all">Все статьи</option>{calendar.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Контрагент<select value={calendar.counterpartyId} onChange={(e) => calendar.setCounterpartyId(e.target.value)}><option value="all">Все контрагенты</option>{calendar.counterparties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Статус<select value={calendar.status} onChange={(e) => calendar.setStatus(e.target.value)}><option value="all">Все статусы</option>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className={calendar.onlyGaps ? 'button danger' : 'button'} onClick={() => calendar.setOnlyGaps((v) => !v)}>Только разрывы</button></div></details><details><summary><i className="fa-solid fa-building-columns" /> Счета</summary><div className="accountMini">{accountRows.map((row) => <span key={row.name}>{row.name}<b>{money(row.balance)}</b></span>)}</div></details></section></aside>
}

function LoginScreen({ login, setLogin, users, onAutoLogin, onSubmit }: { login: LoginState; setLogin: Dispatch<SetStateAction<LoginState>>; users: User[]; onAutoLogin: (user: User) => void; onSubmit: (event: FormEvent) => void }) {
  const [autoUserId, setAutoUserId] = useState('')
  const selectedUser = users.find((item) => item.id === autoUserId) ?? users[0]
  useEffect(() => { if (!autoUserId && users[0]) setAutoUserId(users[0].id) }, [autoUserId, users])
  return <section className="loginScreen"><form className="loginCard" onSubmit={onSubmit}><i className="fa-solid fa-building-columns loginIcon" /><h2>Вход в систему</h2><p>Введите учётные данные или используйте debug авто-вход.</p><label>Email<input autoFocus type="email" value={login.email} onChange={(e) => setLogin((state) => ({ ...state, email: e.target.value }))} /></label><label>Пароль<input type="password" value={login.password} onChange={(e) => setLogin((state) => ({ ...state, password: e.target.value }))} /></label>{login.error && <div className="formError">{login.error}</div>}<button className="button primary wide" disabled={login.loading}>{login.loading ? 'Входим…' : 'Войти'}</button><div className="quickLogin"><label>Debug авто-вход<select value={autoUserId} onChange={(e) => setAutoUserId(e.target.value)}>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button wide" type="button" disabled={!selectedUser} onClick={() => selectedUser && onAutoLogin(selectedUser)}>Войти выбранным аккаунтом</button></div></form></section>
}
function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <span className="metric"><small>{label}</small><em className={tone}>{value}</em></span> }
function Approvals({ flows, counterparties, approvalLog, onStatus }: { flows: CashFlow[]; counterparties: DirectoryItem[]; approvalLog: { paymentId: string; decision: PaymentStatus; comment: string; date: string }[]; onStatus: (id: string, status: PaymentStatus, comment?: string) => void }) { const [comments, setComments] = useState<Record<string, string>>({}); const nameOf = (id: string) => counterparties.find((i) => i.id === id)?.name ?? id; return <section className="cards">{flows.length === 0 ? <Empty title="Нет заявок на согласование" /> : flows.map((flow) => <article className="panel card" key={flow.id}><h2>{nameOf(flow.counterpartyId)}</h2><p>{flow.purpose}</p><strong>{money(flow.amount)}</strong><label>Комментарий<input value={comments[flow.id] ?? ''} onChange={(e) => setComments((s) => ({ ...s, [flow.id]: e.target.value }))} /></label><div className="actions"><button className="button primary" onClick={() => onStatus(flow.id, 'approved', comments[flow.id])}>Утвердить</button><button className="button danger" onClick={() => onStatus(flow.id, 'rejected', comments[flow.id])}>Отклонить</button></div></article>)}<article className="panel card"><h2>Журнал согласований</h2>{approvalLog.length === 0 ? <p>Пока пусто.</p> : approvalLog.map((row) => <p key={`${row.paymentId}-${row.date}`}>{row.date} · {row.paymentId} · {statusLabel[row.decision]} · {row.comment || 'без комментария'}</p>)}</article></section> }
function Register({ approvedPayments, accounts, counterparties, onCreate, onExport, onPaid }: { approvedPayments: CashFlow[]; accounts: Account[]; counterparties: DirectoryItem[]; onCreate: (accountId: string, date: string) => void; onExport: (flows: CashFlow[]) => void; onPaid: (ids: string[]) => void }) { const [accountId, setAccountId] = useState(accounts[0]?.id ?? ''); const [date, setDate] = useState(approvedPayments[0]?.date ?? '2026-06-01'); const account = accounts.find((a) => a.id === accountId); const scoped = approvedPayments.filter((flow) => flow.accountId === accountId && flow.date === date).sort((a, b) => ({ high: 0, normal: 1, low: 2 }[a.priority ?? 'normal'] - { high: 0, normal: 1, low: 2 }[b.priority ?? 'normal'])); const selected = scoped.filter((_flow, index) => scoped.slice(0, index + 1).reduce((sum, f) => sum + f.amount, 0) <= (account?.openingBalance ?? 0)); const total = selected.reduce((sum, flow) => sum + flow.amount, 0); const nameOf = (id: string) => counterparties.find((i) => i.id === id)?.name ?? id; useEffect(() => { if (!accountId && accounts[0]) setAccountId(accounts[0].id) }, [accountId, accounts]); return <section className="treasuryGrid"><article className="panel treasuryHero"><span className="eyebrow">Казначей</span><h2>Реестр платежей</h2><p>Согласованные заявки, приоритет и доступный остаток — без лишней ручной сборки.</p><div className="registryControls"><label>Счёт<select value={accountId} onChange={(e) => setAccountId(e.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div><div className="total"><span>К оплате</span><strong>{money(total)}</strong></div><div className="actions"><button className="button primary" disabled={!accountId || selected.length === 0} onClick={() => onCreate(accountId, date)}>Сформировать</button><button className="button" disabled={selected.length === 0} onClick={() => onExport(selected)}>Выгрузить</button><button className="button" disabled={selected.length === 0} onClick={() => onPaid(selected.map((f) => f.id))}>Оплачено</button></div></article><article className="panel"><h2>Очередь</h2>{selected.length === 0 ? <p>Нет заявок на выбранную дату или не хватает остатка.</p> : selected.map((flow) => <div className="registerRow" key={flow.id}><span>{nameOf(flow.counterpartyId)} · {flow.priority}</span><strong>{money(flow.amount)}</strong></div>)}</article></section> }
function Reports({ days, flows, counterparties, onExport }: { days: CalendarDay[]; flows: CashFlow[]; counterparties: DirectoryItem[]; onExport: () => void }) { const gaps = days.filter((day) => day.hasGap); const periodStart = days[0]?.date ?? ''; const overdue = flows.filter((flow) => flow.type === 'payment' && flow.date < periodStart && flow.status !== 'paid'); return <section className="cards"><article className="panel card"><h2>Ближайшие разрывы</h2>{gaps.slice(0, 5).map((day) => <p key={day.date}>{shortDate(day.date)} · {money(day.endBalance)}</p>)}<button className="button wide" onClick={onExport}>Выгрузить отчёты</button></article><article className="panel card"><h2>План/факт</h2><p>Поступления: {money(flows.filter((f) => f.type === 'income').reduce((s, f) => s + f.amount, 0))}</p><p>Платежи: {money(flows.filter((f) => f.type === 'payment' && f.status !== 'rejected').reduce((s, f) => s + f.amount, 0))}</p></article><article className="panel card"><h2>Просроченные неоплаченные</h2>{overdue.map((flow) => <p key={flow.id}>{counterparties.find((i) => i.id === flow.counterpartyId)?.name} · {money(flow.amount)}</p>)}</article></section> }
function Admin({ users }: { users: User[] }) { return <section className="cards"><List title="Пользователи и роли" rows={users.map((u) => `${u.name} · ${roleLabel[u.role]}`)} /><List title="Система" rows={['Ролевой доступ активен', 'Данные запрашиваются через API', 'Перенос платежей сохраняется сразу', 'Debug авто-вход сохранён']} /></section> }
function List({ title, rows }: { title: string; rows: string[] }) { return <article className="panel card"><h2>{title}</h2>{rows.map((row) => <p key={row}>{row}</p>)}</article> }
function Empty({ title }: { title: string }) { return <section className="panel empty"><h2>{title}</h2><p>Ничего делать не нужно.</p></section> }

function NewFlowModal({ date, accounts, counterparties, categories, onClose, onSubmit }: { date: string; accounts: Account[]; counterparties: DirectoryItem[]; categories: DirectoryItem[]; onClose: () => void; onSubmit: (draft: FlowDraft) => void }) {
  const [type, setType] = useState<'payment' | 'income'>('payment')
  const typedCategories = categories.filter((category) => !category.type || category.type === type)
  const [draft, setDraft] = useState({ date, accountId: accounts[0]?.id ?? '', counterpartyId: counterparties[0]?.id ?? '', categoryId: typedCategories[0]?.id ?? '', amount: '0', purpose: '', priority: 'normal' as FlowDraft['priority'] })
  useEffect(() => { setDraft((state) => ({ ...state, categoryId: typedCategories[0]?.id ?? '' })) }, [type])
  const submit = (event: FormEvent) => {
    event.preventDefault()
    const amount = Number(draft.amount)
    if (!draft.accountId || !draft.counterpartyId || !draft.categoryId || amount <= 0) return
    onSubmit({ ...draft, type, amount, status: type === 'payment' ? 'draft' : undefined })
  }
  return <div className="modalBackdrop" onClick={onClose}><form className="modal formGrid" onSubmit={submit} onClick={(e) => e.stopPropagation()}><header><h2>Новое движение</h2><button className="iconButton" type="button" onClick={onClose}><i className="fa-solid fa-xmark" /></button></header><label>Тип<select value={type} onChange={(e) => setType(e.target.value as 'payment' | 'income')}><option value="payment">Заявка на платёж</option><option value="income">Поступление</option></select></label><label>Дата<input type="date" value={draft.date} onChange={(e) => setDraft((s) => ({ ...s, date: e.target.value }))} /></label><label>Счёт<select value={draft.accountId} onChange={(e) => setDraft((s) => ({ ...s, accountId: e.target.value }))}>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Контрагент<select value={draft.counterpartyId} onChange={(e) => setDraft((s) => ({ ...s, counterpartyId: e.target.value }))}>{counterparties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Статья<select value={draft.categoryId} onChange={(e) => setDraft((s) => ({ ...s, categoryId: e.target.value }))}>{typedCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Сумма<input type="number" min="0.01" step="0.01" value={draft.amount} onChange={(e) => setDraft((s) => ({ ...s, amount: e.target.value }))} /></label>{type === 'payment' && <label>Приоритет<select value={draft.priority} onChange={(e) => setDraft((s) => ({ ...s, priority: e.target.value as FlowDraft['priority'] }))}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option></select></label>}<label>Назначение<input value={draft.purpose} onChange={(e) => setDraft((s) => ({ ...s, purpose: e.target.value }))} /></label><button className="button primary wide">Создать</button></form></div>
}
export default App
