import { useEffect, useState, type Dispatch, type FormEvent, type SetStateAction } from 'react'
import './App.css'
import { type Account, type CalendarDay, type CashFlow, type DirectoryItem, type FlowDraft, type PaymentStatus, type User } from './apiFacade'
import { money, shortDate } from './format'
import { type LoginState, pageIcon, pageLabel, roleLabel, statusLabel, usePaymentCalendar } from './usePaymentCalendar'

function App() {
  const calendar = usePaymentCalendar()
  const [newDate, setNewDate] = useState<string | null>(null)
  const nameOf = (items: DirectoryItem[], id: string) => items.find((item) => item.id === id)?.name ?? id
  const accountName = (id: string) => calendar.accounts.find((account) => account.id === id)?.name ?? id
  const canMove = (flow: CashFlow) => flow.type === 'payment' && ['draft', 'approval', 'approved'].includes(flow.status ?? 'draft')

  return <main className="appShell">
    <aside className="rail">
      <div className="logo"><i className="fa-solid fa-wallet" /></div>
      <nav>{calendar.availablePages.map((item) => <button className={calendar.page === item ? 'active' : ''} key={item} title={pageLabel[item]} onClick={() => calendar.setPage(item)}><i className={`fa-solid ${pageIcon[item]}`} /><span>{pageLabel[item]}</span></button>)}</nav>
      {calendar.user && <button className="avatar" title="Выйти" onClick={calendar.logout}>{calendar.user.name.slice(0, 1)}</button>}
    </aside>

    <section className="workspace">
      <header className="topbar"><div><span className="eyebrow">{calendar.user ? `${roleLabel[calendar.user.role]} · ${calendar.user.name}` : 'Вход'}</span><h1>{calendar.user ? pageLabel[calendar.page] : 'Платёжный календарь'}</h1></div>{calendar.user && <button className="button primary" onClick={() => setNewDate(`${calendar.period}-01`)}>Создать движение</button>}</header>
      {calendar.message && <button className="toast" onClick={() => calendar.setMessage('')}>{calendar.message}</button>}

      {!calendar.user && <LoginScreen login={calendar.login} setLogin={calendar.setLogin} users={calendar.users} onAutoLogin={calendar.autoLogin} onSubmit={calendar.submitLogin} />}
      {calendar.user && calendar.page === 'calendar' && <><Kpis days={calendar.days} approvedPayments={calendar.approvedPayments} monthEnd={calendar.monthEnd} nearestGap={calendar.nearestGap} /><section className="panel controls"><label>Счёт<select value={calendar.accountId} onChange={(e) => calendar.setAccountId(e.target.value)}><option value="all">Все счета</option>{calendar.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Период<input type="month" value={calendar.period} onChange={(e) => calendar.setPeriod(e.target.value)} /></label><button className={calendar.onlyGaps ? 'iconButton danger' : 'iconButton'} title="Только разрывы" onClick={() => calendar.setOnlyGaps((v) => !v)}><i className="fa-solid fa-triangle-exclamation" /></button></section><section className="calendar">{calendar.visibleDays.map((day) => <article className={day.hasGap ? 'day gap' : 'day'} key={day.date} onClick={() => calendar.setSelectedDay(day)} onDragOver={(e) => e.preventDefault()} onDrop={() => calendar.movePayment(day.date)}><span className="dayTop"><strong>{shortDate(day.date)}</strong><span>{day.hasGap && <b>Разрыв</b>}<button className="iconButton miniIcon plusButton" title="Новая заявка на этот день" onClick={(e) => { e.stopPropagation(); setNewDate(day.date) }}><i className="fa-solid fa-plus" /></button></span></span><Metric label="Приход" value={money(day.income)} tone="positive" /><Metric label="Расход" value={money(day.outcome)} tone="negative" /><Metric label="Остаток" value={money(day.endBalance)} tone={day.endBalance < 0 ? 'negative' : ''} /><div className="flowContainer">{day.flows.length === 0 ? <span className="placeholder">Нет движений. Перетащите платёж сюда.</span> : <ul>{day.flows.slice(0, 4).map((flow) => <li draggable={canMove(flow)} key={flow.id} onDragStart={(e) => { if (!canMove(flow)) return; e.stopPropagation(); calendar.setDraggedId(flow.id); calendar.setDragPoint({ x: e.clientX, y: e.clientY }) }} className={flow.type}>{flow.type === 'income' ? '+' : canMove(flow) ? '↕' : '•'} {nameOf(calendar.counterparties, flow.counterpartyId)} · {money(flow.amount)}</li>)}{day.flows.length > 4 && <li className="moreFlow">+{day.flows.length - 4} ещё</li>}</ul>}</div></article>)}</section></>}
      {calendar.user && calendar.page === 'requests' && <FlowTable title="Заявки на платёж" flows={calendar.payments} counterparties={calendar.counterparties} categories={calendar.categories} accounts={calendar.accounts} onStatus={calendar.setPaymentStatus} />}
      {calendar.user && calendar.page === 'receipts' && <FlowTable title="Плановые поступления" flows={calendar.receipts} counterparties={calendar.counterparties} categories={calendar.categories} accounts={calendar.accounts} />}
      {calendar.user && calendar.page === 'approvals' && <Approvals flows={calendar.needsApproval} counterparties={calendar.counterparties} onStatus={calendar.setPaymentStatus} />}
      {calendar.user && calendar.page === 'register' && <Register approvedPayments={calendar.approvedPayments} accounts={calendar.accounts} counterparties={calendar.counterparties} onCreate={calendar.createRegistry} />}
      {calendar.user && calendar.page === 'reports' && <Reports days={calendar.days} flows={calendar.flows} counterparties={calendar.counterparties} />}
      {calendar.user && calendar.page === 'directories' && <Directories accounts={calendar.accounts} counterparties={calendar.counterparties} categories={calendar.categories} />}
      {calendar.user && calendar.page === 'admin' && <Admin users={calendar.users} />}
    </section>

    {calendar.selectedDay && <div className="modalBackdrop" onClick={() => calendar.setSelectedDay(null)}><section className="modal" onClick={(e) => e.stopPropagation()} onDragOver={(e) => e.preventDefault()} onDrop={() => calendar.movePayment(calendar.selectedDay!.date)}><header><h2>{shortDate(calendar.selectedDay.date)}</h2><div className="actions"><button className="iconButton plusButton" title="Новая заявка на этот день" onClick={() => setNewDate(calendar.selectedDay!.date)}><i className="fa-solid fa-plus" /></button><button className="iconButton" title="Закрыть" onClick={() => calendar.setSelectedDay(null)}><i className="fa-solid fa-xmark" /></button></div></header><div className="modalDropZone"><i className="fa-solid fa-arrows-up-down-left-right" /> Перетащите платёж сюда, чтобы перенести на этот день</div>{calendar.selectedDay.flows.length === 0 ? <p>Движений нет.</p> : calendar.selectedDay.flows.map((flow) => <div className="flowCard" draggable={canMove(flow)} onDragStart={(e) => { if (!canMove(flow)) return; calendar.setDraggedId(flow.id); calendar.setDragPoint({ x: e.clientX, y: e.clientY }) }} key={flow.id}><span>{nameOf(calendar.categories, flow.categoryId)} · {nameOf(calendar.counterparties, flow.counterpartyId)}</span><strong className={flow.type === 'income' ? 'positive' : 'negative'}>{flow.type === 'income' ? '+' : '-'} {money(flow.amount)}</strong><small>{accountName(flow.accountId)} · {flow.purpose}</small></div>)}</section></div>}
    {newDate && <NewFlowModal date={newDate} accounts={calendar.accounts} counterparties={calendar.counterparties} categories={calendar.categories} onClose={() => setNewDate(null)} onSubmit={(draft) => { calendar.createFlow(draft); setNewDate(null) }} />}
    {calendar.draggedFlow && <div className="dragPreview" style={{ left: calendar.dragPoint.x + 14, top: calendar.dragPoint.y + 14 }}><strong>{nameOf(calendar.counterparties, calendar.draggedFlow.counterpartyId)}</strong><span>{money(calendar.draggedFlow.amount)}</span></div>}
  </main>
}

function LoginScreen({ login, setLogin, users, onAutoLogin, onSubmit }: { login: LoginState; setLogin: Dispatch<SetStateAction<LoginState>>; users: User[]; onAutoLogin: (user: User) => void; onSubmit: (event: FormEvent) => void }) {
  const [autoUserId, setAutoUserId] = useState('')
  const selectedUser = users.find((item) => item.id === autoUserId) ?? users[0]
  useEffect(() => { if (!autoUserId && users[0]) setAutoUserId(users[0].id) }, [autoUserId, users])
  return <section className="loginScreen"><form className="loginCard" onSubmit={onSubmit}><i className="fa-solid fa-building-columns loginIcon" /><h2>Вход в систему</h2><p>Введите учётные данные или используйте debug авто-вход.</p><label>Email<input autoFocus type="email" value={login.email} onChange={(e) => setLogin((state) => ({ ...state, email: e.target.value }))} /></label><label>Пароль<input type="password" value={login.password} onChange={(e) => setLogin((state) => ({ ...state, password: e.target.value }))} /></label>{login.error && <div className="formError">{login.error}</div>}<button className="button primary wide" disabled={login.loading}>{login.loading ? 'Входим…' : 'Войти'}</button><div className="quickLogin"><label>Debug авто-вход<select value={autoUserId} onChange={(e) => setAutoUserId(e.target.value)}>{users.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button wide" type="button" disabled={!selectedUser} onClick={() => selectedUser && onAutoLogin(selectedUser)}>Войти выбранным аккаунтом</button></div></form></section>
}
function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <span className="metric"><small>{label}</small><em className={tone}>{value}</em></span> }
function Kpis({ days, approvedPayments, monthEnd, nearestGap }: { days: CalendarDay[]; approvedPayments: CashFlow[]; monthEnd: number; nearestGap?: CalendarDay }) { return <section className="kpis"><div><span>Остаток на конец периода</span><strong className={monthEnd < 0 ? 'negative' : ''}>{money(monthEnd)}</strong></div><div><span>Ближайший разрыв</span><strong className="negative">{nearestGap ? shortDate(nearestGap.date) : 'нет'}</strong></div><div><span>Согласовано к оплате</span><strong>{money(approvedPayments.reduce((sum, flow) => sum + flow.amount, 0))}</strong></div><div><span>Дней с разрывом</span><strong>{days.filter((day) => day.hasGap).length}</strong></div></section> }
function FlowTable({ title, flows, counterparties, categories, accounts, onStatus }: { title: string; flows: CashFlow[]; counterparties: DirectoryItem[]; categories: DirectoryItem[]; accounts: Account[]; onStatus?: (id: string, status: PaymentStatus) => void }) { const nameOf = (items: DirectoryItem[], id: string) => items.find((item) => item.id === id)?.name ?? id; return <section className="panel"><h2>{title}</h2><table><thead><tr><th>Дата</th><th>Контрагент</th><th>Статья</th><th>Счёт</th><th>Сумма</th><th>Статус</th><th></th></tr></thead><tbody>{flows.map((flow) => <tr key={flow.id}><td>{shortDate(flow.date)}</td><td>{nameOf(counterparties, flow.counterpartyId)}</td><td>{nameOf(categories, flow.categoryId)}</td><td>{accounts.find((a) => a.id === flow.accountId)?.name}</td><td className={flow.type === 'income' ? 'positive' : 'negative'}>{money(flow.amount)}</td><td>{flow.status ? <span className={`badge ${flow.status}`}>{statusLabel[flow.status]}</span> : 'План'}</td><td>{onStatus && flow.status === 'draft' && <button className="button mini" onClick={() => onStatus(flow.id, 'approval')}>На согласование</button>}</td></tr>)}</tbody></table></section> }
function Approvals({ flows, counterparties, onStatus }: { flows: CashFlow[]; counterparties: DirectoryItem[]; onStatus: (id: string, status: PaymentStatus) => void }) { const nameOf = (id: string) => counterparties.find((i) => i.id === id)?.name ?? id; return <section className="cards">{flows.length === 0 ? <Empty title="Нет заявок на согласование" /> : flows.map((flow) => <article className="panel card" key={flow.id}><h2>{nameOf(flow.counterpartyId)}</h2><p>{flow.purpose}</p><strong>{money(flow.amount)}</strong><div className="actions"><button className="button primary" onClick={() => onStatus(flow.id, 'approved')}>Утвердить</button><button className="button danger" onClick={() => onStatus(flow.id, 'rejected')}>Отклонить</button></div></article>)}</section> }
function Register({ approvedPayments, accounts, counterparties, onCreate }: { approvedPayments: CashFlow[]; accounts: Account[]; counterparties: DirectoryItem[]; onCreate: (accountId: string, date: string) => void }) { const [accountId, setAccountId] = useState(accounts[0]?.id ?? ''); const [date, setDate] = useState(approvedPayments[0]?.date ?? '2026-06-01'); const scoped = approvedPayments.filter((flow) => flow.accountId === accountId && flow.date === date); const total = scoped.reduce((sum, flow) => sum + flow.amount, 0); const nameOf = (id: string) => counterparties.find((i) => i.id === id)?.name ?? id; useEffect(() => { if (!accountId && accounts[0]) setAccountId(accounts[0].id) }, [accountId, accounts]); return <section className="panel"><h2>Реестр платежей</h2><p>Формируется из согласованных заявок по счёту и дате.</p><div className="registryControls"><label>Счёт<select value={accountId} onChange={(e) => setAccountId(e.target.value)}>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label><label>Дата<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div>{scoped.length === 0 ? <p>Нет согласованных заявок на выбранную дату.</p> : scoped.map((flow) => <div className="registerRow" key={flow.id}><span>{nameOf(flow.counterpartyId)}</span><strong>{money(flow.amount)}</strong></div>)}<div className="total"><span>Итого</span><strong>{money(total)}</strong></div><button className="button primary wide" disabled={!accountId || scoped.length === 0} onClick={() => onCreate(accountId, date)}>Сформировать реестр</button></section> }
function Reports({ days, flows, counterparties }: { days: CalendarDay[]; flows: CashFlow[]; counterparties: DirectoryItem[] }) { const gaps = days.filter((day) => day.hasGap); const periodStart = days[0]?.date ?? ''; const overdue = flows.filter((flow) => flow.type === 'payment' && flow.date < periodStart && flow.status !== 'paid'); return <section className="cards"><article className="panel card"><h2>Ближайшие разрывы</h2>{gaps.slice(0, 5).map((day) => <p key={day.date}>{shortDate(day.date)} · {money(day.endBalance)}</p>)}</article><article className="panel card"><h2>План/факт</h2><p>Поступления: {money(flows.filter((f) => f.type === 'income').reduce((s, f) => s + f.amount, 0))}</p><p>Платежи: {money(flows.filter((f) => f.type === 'payment' && f.status !== 'rejected').reduce((s, f) => s + f.amount, 0))}</p></article><article className="panel card"><h2>Просроченные неоплаченные</h2>{overdue.map((flow) => <p key={flow.id}>{counterparties.find((i) => i.id === flow.counterpartyId)?.name} · {money(flow.amount)}</p>)}</article></section> }
function Directories({ accounts, counterparties, categories }: { accounts: Account[]; counterparties: DirectoryItem[]; categories: DirectoryItem[] }) { return <section className="cards"><List title="Счета и кассы" rows={accounts.map((i) => `${i.name} · ${money(i.openingBalance)}`)} /><List title="Контрагенты" rows={counterparties.map((i) => `${i.name} · ${i.details}`)} /><List title="Статьи движения" rows={categories.map((i) => `${i.name} · ${i.type === 'income' ? 'поступление' : 'списание'}`)} /></section> }
function Admin({ users }: { users: User[] }) { return <section className="cards"><List title="Пользователи и роли" rows={users.map((u) => `${u.name} · ${roleLabel[u.role]}`)} /><List title="Система" rows={['Ролевой доступ активен', 'Данные запрашиваются через API', 'Перенос платежей сохраняется сразу', 'Debug авто-вход сохранён']} /></section> }
function List({ title, rows }: { title: string; rows: string[] }) { return <article className="panel card"><h2>{title}</h2>{rows.map((row) => <p key={row}>{row}</p>)}</article> }
function Empty({ title }: { title: string }) { return <section className="panel empty"><h2>{title}</h2><p>Ничего делать не нужно.</p></section> }

function NewFlowModal({ date, accounts, counterparties, categories, onClose, onSubmit }: { date: string; accounts: Account[]; counterparties: DirectoryItem[]; categories: DirectoryItem[]; onClose: () => void; onSubmit: (draft: FlowDraft) => void }) {
  const [type, setType] = useState<'payment' | 'income'>('payment')
  const typedCategories = categories.filter((category) => !category.type || category.type === type)
  const [draft, setDraft] = useState({ date, accountId: accounts[0]?.id ?? '', counterpartyId: counterparties[0]?.id ?? '', categoryId: typedCategories[0]?.id ?? '', amount: '0', purpose: '', priority: 'normal' as FlowDraft['priority'] })
  useEffect(() => { setDraft((state) => ({ ...state, categoryId: typedCategories[0]?.id ?? '' })) }, [type])
  const submit = (event: FormEvent) => {
    event.preventDefault()
    const amount = Number(draft.amount)
    if (!draft.accountId || !draft.counterpartyId || !draft.categoryId || amount <= 0) return
    onSubmit({ ...draft, type, amount, status: type === 'payment' ? 'draft' : undefined })
  }
  return <div className="modalBackdrop" onClick={onClose}><form className="modal formGrid" onSubmit={submit} onClick={(e) => e.stopPropagation()}><header><h2>Новое движение</h2><button className="iconButton" type="button" onClick={onClose}><i className="fa-solid fa-xmark" /></button></header><label>Тип<select value={type} onChange={(e) => setType(e.target.value as 'payment' | 'income')}><option value="payment">Заявка на платёж</option><option value="income">Поступление</option></select></label><label>Дата<input type="date" value={draft.date} onChange={(e) => setDraft((s) => ({ ...s, date: e.target.value }))} /></label><label>Счёт<select value={draft.accountId} onChange={(e) => setDraft((s) => ({ ...s, accountId: e.target.value }))}>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Контрагент<select value={draft.counterpartyId} onChange={(e) => setDraft((s) => ({ ...s, counterpartyId: e.target.value }))}>{counterparties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Статья<select value={draft.categoryId} onChange={(e) => setDraft((s) => ({ ...s, categoryId: e.target.value }))}>{typedCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Сумма<input type="number" min="0.01" step="0.01" value={draft.amount} onChange={(e) => setDraft((s) => ({ ...s, amount: e.target.value }))} /></label>{type === 'payment' && <label>Приоритет<select value={draft.priority} onChange={(e) => setDraft((s) => ({ ...s, priority: e.target.value as FlowDraft['priority'] }))}><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option></select></label>}<label>Назначение<input value={draft.purpose} onChange={(e) => setDraft((s) => ({ ...s, purpose: e.target.value }))} /></label><button className="button primary wide">Создать</button></form></div>
}
export default App
